spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
management:
  endpoints:
    web:
      exposure:
        include: '*'
