spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
redis:
  host: localhost
  maxTotal: 5
  maxIdle: 5
  testOnBorrow: true
#  max_total:3
#  max_idle: 5
#  test_on_borrow: true
