spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    cache-names: coffee
    redis:
      time-to-live: 5000
      cache-null-values: false
  redis:
    host: localhost
redis:
  host: localhost
  maxTotal: 5
  maxIdle: 5
  testOnBorrow: true
#  max_total:3
#  max_idle: 5
#  test_on_borrow: true
