spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    lettuce:
      pool:
        max-idle: 5
        max-active: 5
    host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'